### ISSUE TITLE
Enhance possible swagger configuration options

### ISSUE THREAD

**Issue by jinahya** [sdaschner/jaxrs-analyzer-maven-plugin#10]
I wonder if there is a way to customize `"schemes": ["http"]` part, say, with `https`.

How would it like if plugin can be configured with some backend-specific values?

``` xml
<properties>
  <swagger.schemas>http https</swagger.schemas>
<properties>
```

**Comment by sdaschner** [comment]
Currently not yet. This could be definitely added to the configuration, however, I'm just wondering whether the configuration will not be overloaded with options...

But yes I'm thinking about an option. Thanks for your suggestion!

**Comment by sdaschner** [comment]
Added [Swagger schemes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swaggerSchemes) in 1ca0d5f. I'll update the snapshot build and the documentation shortly.

They will be configurable in the Maven plugin as follows:

```
<swaggerSchemes>https</swaggerSchemes>
```

or

```
<swaggerSchemes>
    <swaggerScheme>http</swaggerScheme>
    <swaggerScheme>https</swaggerScheme>
</swaggerSchemes>
```

**Comment by jinahya** [comment]
Any release plan including this feature?

**Comment by sdaschner** [comment]
Yes, we're way behind publishing the next version... The problem is that the internals have been changed from Javassist to ASM -- which is an improvement in multiple ways but that took some time. Hopefully soon :-) Sorry for the delay!
