### ISSUE TITLE
basic authentication headers

### ISSUE THREAD

**Issue by ofirmgr** [sdaschner/jaxrs-analyzer-maven-plugin#15]
I managed to run the maven plugin on my jaxrs server rest API but I"m using dropwizard basic authentication (@Auth PrincipalImpl) and when generating the swagger json there was no authentication header. do you have support for that?

**Comment by sdaschner** [comment]
No, the Analyzer currently only supports Java EE standards -- mainly JSR 339.

Please see [my answer](https://github.com/sdaschner/jaxrs-analyzer/issues/60#issuecomment-226261108) on a similar question, why I'm currently not planning to add authentication support.

**Comment by sdaschner** [comment]
Anyway, if you have an idea how the plugin could be enhanced (maybe some kind of configuration, etc.), without the attempt to automatically gather that information (bc/ I argue that won't work quite reliably), please let me know, I'm happy for all kind of suggestions.
