### ISSUE TITLE
Maven dependency issue

### ISSUE THREAD

**Issue by mitya-multiplayer** [sdaschner/jaxrs-analyzer-maven-plugin#17]
Could you clarify which version should I use to generate swagger definition. Version 0.9 seems generating only plaintext and ignores other options. 
I tried to install locally 0.10-SNAPSHOT but it did not work for various reasons.
Thanks

**Comment by sdaschner** [comment]
All version support the Swagger output. Just include `<backend>swagger</backend>` into the plugin configuration, as shown in the readme. Also could you tell me why the `0.10-SNAPSHOT` didn't work -- maybe post a snippet of the Maven log?

**Comment by mitya-multiplayer** [comment]
I did - but that did not help me - I always got Plain Text :(

**Comment by mitya-multiplayer** [comment]
As for problem with the installation:
One of the tests fails: 
test(com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzerTest): expected:<[rest]> but was:<[]>

I had to comment it out.

After I installed both jaxrs-analyzer and jaxrs-analyzer-maven-plugin I was unable to run analyzer: I get this error:
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs (default-cli) on project getcharter-api: Execution default-cli of goal com.sebastian-daschner:jaxrs-ana
lyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs failed: A required class was missing while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs: io/dropwizard/Configuration

0.9 works fine at the same time - it just produces plain text instead of swagger as requested

**Comment by mitya-multiplayer** [comment]
Here is my plugin configuration:

`````` <plugin>
        <groupId>com.sebastian-daschner</groupId>
        <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
        <version>0.10-SNAPSHOT</version>
        <executions>
          <execution>
            <goals>
              <goal>analyze-jaxrs</goal>
            </goals>
            <configuration>
              <!-- Available backends are plaintext (default), swagger and asciidoc -->
              <backend>swagger</backend>
              <!-- Domain of the deployed project, defaults to example.com -->
              <deployedDomain>api.example.com</deployedDomain>
            </configuration>
          </execution>
        </executions>
      </plugin>```
``````

**Comment by sdaschner** [comment]
The test fails if you run all the unit tests in the IDE, that is because of a test concurrency issue. If you run them via the Maven build it should be fine.

Can you provide more error information / stacktrace of the error above?

The configuration seems ok, that should work like this... So if you just change `0.10-SNAPSHOT` to `0.9` in your pom-code above then it works?

**Comment by mitya-multiplayer** [comment]
Yes, if I switch it to 0,9 - it works. But produces plain text rather than swagger.

**Comment by sdaschner** [comment]
As of yesterday I've published the `0.10` version. What if you change to that one (without the SNAPSHOT)?

**Comment by mitya-multiplayer** [comment]
Hello, thanks for the update!

I tried 0.10 and this is what I got:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.359 s
[INFO] Finished at: 2016-10-19T11:51:34-07:00
[INFO] Final Memory: 21M/974M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs (default-cli) on project getcharter-api: Execution default-cli of goal com.sebastian-daschner:jaxrs-analyzer-mav
en-plugin:0.10:analyze-jaxrs failed: A required class was missing while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs: io/dropwizard/Configuration
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/yateam/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.10/jaxrs-analyzer-maven-plugin-0.10.jar
[ERROR] urls[1] = file:/C:/Users/yateam/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.10/jaxrs-analyzer-0.10.jar
[ERROR] urls[2] = file:/C:/Users/yateam/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: io.dropwizard.Configuration
```

Not sure what this means - I have a configuration class in my application. It extends io.dropwizard.Configuration

**Comment by sdaschner** [comment]
Hmm... that sounds like a clash of (transitive) dependencies.

Maybe try to clean your Maven repository -- delete the folders in ~/.m2/repository (or whatever location that is).
If that doesn't help could you please give me more information on
- the used Maven version
- the used (technically relevant) dependencies in your project
- the (relevant snippets) of the output when building the project with the `-X` debug flag

Thanks in advance!

**Comment by sdaschner** [comment]
Oh and what you could also try is using the Standalone version of the Analyzer, as described [here](https://github.com/sdaschner/jaxrs-analyzer/blob/master/Documentation.adoc#standalone), that one shouldn't collide with these dependencies above.

**Comment by sdaschner** [comment]
Could you please retry with the `0.11-SNAPSHOT` version?

**Comment by mitya-multiplayer** [comment]
Thanks!
Sure I will try. Was busy on a different project.

**Comment by mitya-multiplayer** [comment]
Sorry, took really long time. Version 0.12 works fine!
Thanks

**Comment by mitya-multiplayer** [comment]
Btw, I might open another issue on jaxrs-analyzer project - but the problem with failing test still persists. The test passes if I run it from Intellij IDEA, but fails if I run `mvn test`.

**Comment by sdaschner** [comment]
Glad the new version works. Will look into the testing issue, thanks :)
