### ISSUE TITLE
Include own class loader

### ISSUE THREAD

**Issue by cthiebaud** [sdaschner/jaxrs-analyzer-maven-plugin#18]
Hi, 

after upgrading from 0.9 to 0.10, my maven builds failed with several different issues (lots of trial an error...), all related to class loading, e.g.

Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/eclipse/aether/repository/RemoteRepository

Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.eclipse.aether.resolution.MetadataRequest.<init> (...)

Exception in thread "main" java.lang.IllegalAccessError: org/eclipse/sisu/inject/MildElements$Itr

etc.

The project I am building is a bit special, as it is a REST interface to maven central using aether as internal lib.

I eventually understood that the new version through org.objectweb.asm.ClassReader(final String name) loads classes in the system class loader. After that, maven crashes if you happen to have loaded internal maven or aether classes.

The solution is to use your own class loader then to feed the class into ClassReader(final byte[] b) or ClassReader(final InputStream is).

Or a workaround (easier at least for me to develop) would be to implement some parameter to filter out some given paths in JAXRSAnalyzerMojo.getDependencies() before calling asm.

thanks for this great code, anyway.

**Comment by cthiebaud** [comment]
To reproduce the issue:

```
git clone https://github.com/aequologica/quintessence.git
cd quintessence/
checkout master
mvn clean install

```

should work fine, and you should see "jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs" in the logs

then save this diff in patch.diff

```

diff --git a/pom.xml b/pom.xml
index 83d6c4d..d2fda88 100644
--- a/pom.xml
+++ b/pom.xml
@@ -53,4 +53,21 @@
         <url>https://github.com/aequologica/quintessence</url>
     </scm>

+    <build>
+        <plugins>
+            <plugin>
+                <groupId>com.sebastian-daschner</groupId>
+                <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
+                <version>0.10</version>
+                <executions>
+                    <execution>
+                        <goals>
+                            <goal>analyze-jaxrs</goal>
+                        </goals>
+                    </execution>
+                </executions>
+            </plugin>
+        </plugins>
+    </build>
+
 </project>
\ No newline at end of file

```

then

```
git apply patch.diff
mvn clean install 

```

should fail now with 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project quintessence-core: Execution default-install of goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-install-plugin:2.5.2:install: java.lang.LinkageError: loader constraint violation: when resolving method "org.eclipse.aether.util.artifact.SubArtifact.<init>(Lorg/eclipse/aether/artifact/Artifact;Ljava/lang/String;Ljava/lang/String;)V" the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) of the current class, org/apache/maven/artifact/installer/DefaultArtifactInstaller, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/eclipse/aether/util/artifact/SubArtifact, have different Class objects for the type org/eclipse/aether/artifact/Artifact used in the signature
`

**Comment by cthiebaud** [comment]
I did a quick an d dirty patch to both jaxrs-analyzer and jaxrs-analyzer-maven-plugin to use its own classloader instead of system class loader. If fixes my issues. they are here

https://github.com/cthiebaud/jaxrs-analyzer/tree/use_your_own_class_loader
https://github.com/cthiebaud/jaxrs-analyzer-maven-plugin/tree/use_your_own_class_loader

but I do not think the quality is enough for a pull request

**Comment by sdaschner** [comment]
Hi, thanks for the detailed feedback and the reproducer!

Yes, that's quite an issue if you want to load internal classes (used by the Maven plugin here). But maybe it helps if you use the standalone version of the Analyzer? That one doesn't include the Maven Aether and shouldn't collide with these classes then...

Yes, I've been thinking about including an own class loader -- so far it worked to inject into the System class loader, but you're right that would be the better solution -- as the project dependencies can't collide with the JAX-RS Analyzer ones then...

Thanks for the fix, I'll can definitely use that!
