### ISSUE TITLE
Eclipse: Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by okoeth** [sdaschner/jaxrs-analyzer-maven-plugin#2]
Needed to add this to my workspace' lifecycle mapping metadata in Eclipse. Not sure if this is what's intended. But I needed to overcome "plugin execution not covered by lifecycle configuration". 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>com.sebastian-daschner</groupId>
        <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
        <goals>
          <goal>analyze-jaxrs</goal>
        </goals>
        <versionRange>[0.0,)</versionRange>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```

**Comment by florianli** [comment]
In Eclipse try
Window->Preferences->Maven->Lifecycle Mapping->"Open workspace lifcycle mappings metadata"

and add 

```
<pluginExecution>
    <pluginExecutionFilter>
        <groupId>com.sebastian-daschner</groupId>
        <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
        <versionRange>[0.0,)</versionRange>
        <goals>
            <goal>analyze-jaxrs</goal>
        </goals>
    </pluginExecutionFilter>
    <action>
        <execute />
    </action>
</pluginExecution>
```

then

Window->Preferences->Maven->Lifecycle Mapping->"Reload workspace lifcycle mappings metadata"

**Comment by sdaschner** [comment]
Thanks guys for providing that information! Been a while since I had to deal with Eclipse ;-)

Will include that information in the docs as soon I have the time.

**Comment by DanielFTwum** [comment]
This is very cool. However I am missing something.

What maven command do you use to build?

I have followed the above steps but still I am not seeing it generate any documentation.

```
            <plugin>
                <groupId>com.sebastian-daschner</groupId>
                <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
                <version>0.9</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>analyze-jaxrs</goal>
                        </goals>
                        <configuration>
                            <!-- Available backends are plaintext (default), swagger and asciidoc -->
                            <backend>asciidoc</backend>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by sdaschner** [comment]
I normally use `mvn clean install` to build Maven projects. The default phase where the plugin runs is `process-classes`.

**Comment by karthikjai** [comment]
Had to make the following change in the pom.xml to make it work
.......... <executions> <execution> <phase>process-classes</phase>  <goals> .........

**Comment by dwschulze** [comment]
Adding the `<pluginExecutionFilter>` element to Lifecycle Mappings metadata as mentioned above does nothing on Neon.
Has anyone found a way to get rid of this problem on Neon?

**Comment by dwschulze** [comment]
You've got to have the

<lifecycleMappingMetadata>
  <pluginExecutions>

elements as shown by okoeth above, not just the <pluginExecution> element.

**Comment by goyaneo79** [comment]
this worked for me,  thanks dwschulze
