### ISSUE TITLE
How to use this plugin with Java wicket 

### ISSUE THREAD

**Issue by umar320** [sdaschner/jaxrs-analyzer-maven-plugin#20]
Hi,

Is it possible that we can use this plugin to document JAXRS REST APIs which was developed using Java Wicket? Please let me know the way.

Thanks

**Comment by sdaschner** [comment]
If you use JAX-RS in your project it will work out of the box, just use the (Maven) Analyzer as shown in the docs. If you use Wicketstuff REST or Spring or any other framework for REST HTTP functionality it won't work, simply because the Analyzer only knows the JAX-RS standard.

**Comment by umar320** [comment]
Thank you dude.
