### ISSUE TITLE
Empty jaxrs-analyzer folder

### ISSUE THREAD

**Issue by rajani007** [sdaschner/jaxrs-analyzer-maven-plugin#21]
Hi,
I am trying to use the plugin but for some reason it is creating empty jaxrs-analyzer folder.

[INFO] --- jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs (default) @ ServiceQuote ---
[INFO] analyzing JAX-RS resources, using Swagger backend
[INFO] Empty JAX-RS analysis result, omitting output

This is a spring boot application. What am i doing wrong here?

Thanks

**Comment by sdaschner** [comment]
Hi, thanks for using my tool.
The JAX-RS Analyzer only supports analysis of JAX-RS projects. Are you using this technology in your Spring boot application or the standard Spring (REST) controller mechanism?

Spring controllers are not supported by my tool.

**Comment by rajani007** [comment]
Hi,
Thanks for your response. I am using Springboot applications.
