### ISSUE TITLE
tools.jar failure on 0.11

### ISSUE THREAD

**Issue by azell** [sdaschner/jaxrs-analyzer-maven-plugin#22]
Upgrading to 0.11 fails:

`
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.11:analyze-jaxrs (default) on project nextseat-rest: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.11:analyze-jaxrs failed: Plugin com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.8 at specified path /opt/java/jdk1.8.0_102/jre/../lib/tools.jar -> [Help 1]
`

POM:

        <plugin>
          <groupId>com.sebastian-daschner</groupId>
          <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
          <version>0.11</version>
          <executions>
            <execution>
              <goals>
                <goal>analyze-jaxrs</goal>
              </goals>
              <configuration>
                <backend>asciidoc</backend>
                <deployedDomain>xx.yyy.zzz</deployedDomain>
              </configuration>
            </execution>
          </executions>
        </plugin>

MacOS Sierra 10.12.2 (16C67)
JDK 1.8.0_112

**Comment by sdaschner** [comment]
A big thanks for pointing that out! Forgot about the tools.jar being included as a system property. I've been working around that problem the last two days and will publish a new version (`0.12`, since `0.11` is broken and already synced everywhere) soon, hopefully today. Will let you know as soon as the version is out.

**Comment by sdaschner** [comment]
Update: `0.12` is synced.
