### ISSUE TITLE
Provide a way to enhance generated documentation

### ISSUE THREAD

**Issue by vboerchers** [sdaschner/jaxrs-analyzer-maven-plugin#23]
First of all: Thank you for jaxrs-analyzer!

It would be great if it would provide a way to enhance the generated documentation by descriptions to resources and methods either via

* recognizing Swagger annotations
* providing your own annotations
* special Javadoc annotations (to avoid further link dependencies?)
* accepting a yaml/xml/properties file

If such a facility should already exist please add instructions to the plugin documentation.

**Comment by sdaschner** [comment]
Hi, thanks for using my tool!

Funnily just in these days I've finished the first version of JavaDoc support. You can now describe JAX-RS methods and parameters directly in the JavaDoc which will be incorporated into the Swagger output. The feature will be included in version `0.12` (which is just about to be released).

**Comment by vboerchers** [comment]
Wow, great! I'll gladly use the new feature once it's out :-)

**Comment by sdaschner** [comment]
Update: `0.12` is published. Also see https://blog.sebastian-daschner.com/entries/javadoc_jaxrs_analysis

**Comment by jmanteigueiro** [comment]
Is this working in the current version?

**Comment by vboerchers** [comment]
Yes it is

**Comment by jmanteigueiro** [comment]
Can you show me an example? I'm not being able to use it. The produced swagger.json ignores all java docs and swagger annotations..

**Comment by sdaschner** [comment]
Swagger annotations are not supported. You can have a look at the JavaDoc support here: https://blog.sebastian-daschner.com/entries/javadoc_jaxrs_analysis
