### ISSUE TITLE
Error on run : Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/Application

### ISSUE THREAD

**Issue by matfur92** [sdaschner/jaxrs-analyzer-maven-plugin#29]
Hi,
in one of my projects I have this error : 

[INFO] --- jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs (default) @ test ---
[INFO] analyzing JAX-RS resources, using Swagger backend
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.477 s
[INFO] Finished at: 2017-02-01T12:53:44+01:00
[INFO] Final Memory: 23M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs (default) on project test: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs failed: An API incompatibility was encountered while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/Application
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/mat/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.12/jaxrs-analyzer-maven-plugin-0.12.jar
[ERROR] urls[1] = file:/C:/Users/mat/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.12/jaxrs-analyzer-0.12.jar
[ERROR] urls[2] = file:/C:/Users/mat/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

My pom.xml import that dependencies :
![immagine](https://cloud.githubusercontent.com/assets/10245779/22506258/c42971c8-e87f-11e6-9921-e963945c6db6.png)

I'm doing something wrong?
Thanks a lot in advance!

**Comment by matfur92** [comment]
The problem is in the pom.xml
```xml
<dependency> 
      <groupId>javax</groupId> 
      <artifactId>javaee-web-api</artifactId> 
      <version>6.0</version> 
      <scope>provided</scope> 
</dependency> 
```
I replaced **javaee-web-api** with **javaee-api**:
```xml
<dependency> 
      <groupId>javax</groupId> 
      <artifactId>javaee-api</artifactId> 
      <version>6.0</version> 
      <scope>provided</scope> 
</dependency>
```
Now the build is working!

**Comment by sdaschner** [comment]
Great you figured it out! Thanks for sharing, yes the Analyzer assumes that the Java EE 7 API is being used.
