### ISSUE TITLE
compiler IllegalAccessError after including jaxrs-analyzer-maven-plugin

### ISSUE THREAD

**Issue by wumpz** [sdaschner/jaxrs-analyzer-maven-plugin#30]
Hallo,

hab gesehen, dass der andere Issue auch auf deutsch war und schließe mich hiermit (hoffentlich genehm so) an :).

Nachdem ich das Plugin in einen etwas größeren Maven Build eingefügt habe, erhalte ich folgende Exception, allerdings beim Neukompilieren der Testklassen. Das Plugin selber läuft komplett durch und generiert wie gewünscht eine swagger - Ausgabe.

An exception has occurred in the compiler (1.8.0_121). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalAccessError: tried to access class com.sun.tools.javac.comp.MemberEnter$1 from class com.sun.tools.javac.comp.MemberEnter
	at com.sun.tools.javac.comp.MemberEnter.importStaticAll(MemberEnter.java:182)
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:549)
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)

Dies muss aber mit dem Plugin zu tun habe, denn ohne funktioniert alles reibungslos. 

Gruß 

Tobias

**Comment by sdaschner** [comment]
Hallo, danke fürs Einstellen.

Ein ähnlicher Issue wurde ebenfalls schon eingestellt (sdaschner/jaxrs-analyzer#109), deshalb schließe ich den hier.
