### ISSUE TITLE
Unable to generate documentation

### ISSUE THREAD

**Issue by karthikjai** [sdaschner/jaxrs-analyzer-maven-plugin#34]
The maven build runs fine. But it does not seem to generate any documentation. Please see attached my pom.xml and lifecycle-mapping-metadata.xml ( This was suggested in another issue raised earlier)

[pom.xml.txt](https://github.com/sdaschner/jaxrs-analyzer-maven-plugin/files/826674/pom.xml.txt)
[lifecycle-mapping-metadata.xml.txt](https://github.com/sdaschner/jaxrs-analyzer-maven-plugin/files/826675/lifecycle-mapping-metadata.xml.txt)

**Comment by sdaschner** [comment]
You have to include the `<plugin>` without the `<pluginManagement>` directive, otherwise you just declare the version and configuration but don't run it. Please see the [documentation](https://github.com/sdaschner/jaxrs-analyzer-maven-plugin/blob/master/Documentation.adoc).

**Comment by karthikjai** [comment]
Removing the <pluginManagement> directive causes the "PLUGIN EXECUTION NOT COVERED BY LIFECYCLE CONFIGURATION” error in Eclipse. I then tried Window > Preferences > Maven > Errors/Warnings > Plugin executiuon not covered by lifecycle configuration>Ignore. Even after that the documentation is not generated.

**Comment by karthikjai** [comment]
Had to make the following change in the pom.xml to make it work
` ..........
<executions>
<execution>
<phase>process-classes</phase> 
<goals>
.........`

**Comment by sdaschner** [comment]
Yes, glad it finally worked :-)
