### ISSUE TITLE
Add skip option for Maven Plugin

### ISSUE THREAD

**Issue by simdevmon** [sdaschner/jaxrs-analyzer-maven-plugin#38]
It would be nice to have a skip option for the JAX-RS Analyzer Maven Plugin to allow an easy integration into existing Maven profiles, that the plugin gets only executed on CI builds, but not on local ones.

**Comment by sdaschner** [comment]
I think Maven profiles is what you want, that works for all plugins. Just add a profile that activates the plugin and only include it in the CI server, e.g. by some property.

**Comment by simdevmon** [comment]
I have a multi-module Maven project and want to activate **JAXRS-Analyzer** only for one sub project. Profiles are only specified in the parent pom. 
My idea was to add the **jaxrs-analyzer-maven-plugin** only to the parent pom like this:

```
    <properties>
        <skipJaxrsAnalyzer>true</skipJaxrsAnalyzer>
    </properties>
    <profile>
        <id>ci-build</id>
        <build>
            <plugins>
                <plugin>
                    <groupId>com.sebastian-daschner</groupId>
                    <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <configuration>
                                <skip>${skipJaxrsAnalyzer}</skip>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
```

And in the sub project where I want to activate the plugin I can simply activate the property and if I need it for another sub project I can do this very easily as well:

```
    <properties>
        <skipJaxrsAnalyzer>false</skipJaxrsAnalyzer>
    </properties>
```

Or is there any better way to achieve this?

**Comment by sdaschner** [comment]
How about to include the `<plugin>` declaration only in that sub-module and not in the parent or other modules?

**Comment by simdevmon** [comment]
If I include the plugin only to the sub-module, I would have to duplicate the profiles there as well (as far as I know), which I want to avoid to keep the poms as clean as possible. 

Many Maven-plugins such as maven-checkstyle-plugin, findbugs-maven-plugin, maven-pmd-plugin, cobertura-maven-plugin and even maven-surefire-plugin provide skip options, which I find very handy for such use cases. 
I think it is very easy to implement and I would also create a PR if you would accept it.
