### ISSUE TITLE
Neon gives 

### ISSUE THREAD

**Issue by dwschulze** [sdaschner/jaxrs-analyzer-maven-plugin#43]
I get this error from Eclipse Neon:

`Plugin execution not covered by lifecycle configuration: com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14:analyze-jaxrs (execution: default, phase: process-test-classes)`

Changing the lifecycle mappings metadata as shown in [https://github.com/sdaschner/jaxrs-analyzer-maven-plugin/issues/2](url) does nothing.

**Comment by goyaneo79** [comment]
Hi 
i have the same problem, still don't have a fix?
kind regards

**Comment by sdaschner** [comment]
See https://github.com/sdaschner/jaxrs-analyzer-maven-plugin/issues/2

**Comment by SylvainAssemat** [comment]
The link seems to be 404

**Comment by sdaschner** [comment]
Sorry, was wrong link, updated.
