### ISSUE TITLE
Update README to have <phase>package</phase> to avoid warnings in IDE

### ISSUE THREAD

**Issue by iamdvr** [sdaschner/jaxrs-analyzer-maven-plugin#47]
<plugin>
				<groupId>com.sebastian-daschner</groupId>
				<artifactId>jaxrs-analyzer-maven-plugin</artifactId>
				<version>0.16</version>
				<executions>
					<execution>
						**<phase>package</phase>**
						<goals>
							<goal>analyze-jaxrs</goal>
						</goals>
						<configuration>
							<backend>swagger</backend>
							<deployedDomain>example.com</deployedDomain>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by bedag-moo** [comment]
What warning? Maven finds it perfectly ok to not specify a phase here (it will use the plugin's default).

**Comment by sdaschner** [comment]
What IDE are you using? I think this only occurs when using Eclipse.

If specifying the `<phase>` helps, `process-test-classes` is the correct Maven phase.
