### ISSUE TITLE
looking for tools.jar in C:\Program Files\Java\jre1.8.0_162\..\lib\tools.jar

### ISSUE THREAD

**Issue by unclesam123** [sdaschner/jaxrs-analyzer-maven-plugin#51]
Its failing to check dependency as is looking for tools .jar in C:\Program Files\Java\jre1.8.0_162\\..\lib\tools.jar
instead of C:\Program Files\Java\jre1.8.0_162\lib\tools.jar.

Might be is my Eclipse specific ?

**Comment by sdaschner** [comment]
Might be, yes. However, which version are you using? `tools.jar` is not required anymore...

**Comment by unclesam123** [comment]
im using 0.9 to prevent that. 0.14 requires it. Is there anything never?

**Comment by jnorthrup** [comment]
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.16:analyze-jaxrs (default) on project service1: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.16:analyze-jaxrs failed: The location 'E:\opt\jdk10\..\lib\tools.jar' does not exist! -> [Help 1]
