### ISSUE TITLE
swagger.yml output

### ISSUE THREAD

**Issue by fthamura** [sdaschner/jaxrs-analyzer-maven-plugin#8]
can we have output swagger.yml, so we can open it in swagger ui, any tips to use it?

**Comment by sdaschner** [comment]
Hi,

you can indeed open the swagger.json file with Swagger UI. See https://github.com/swagger-api/swagger-ui#use or https://github.com/swagger-api/swagger-ui#swaggerui.

However, a YAML support may be included in a future release.
